spring.application.name=halo Ai
server.port = 9090

spring.security.user.name = moksh
spring.security.user.password = 123

spring.datasource.url=jdbc:postgresql://localhost:5432/Halo_Ai
spring.datasource.username=postgres
spring.datasource.password=beverly@26Marsh

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect